services:
  - type: web
    name: j-tec-video-production-api
    runtime: python

    buildCommand: |
      apt-get update
      apt-get install -y ffmpeg
      pip install -r requirements.txt
      playwright install chromium
      playwright install-deps chromium

    startCommand: |
      uvicorn app.main:app --host 0.0.0.0 --port $PORT
